global:
  params:
    x: 3333
    y: 4444

spring:
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:9999

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"